fix: sync mediatek_filogic patches from kiddin9/Kwrt for 25.12

diff --git a/devices/mediatek_filogic/patches/25-platform.patch b/devices/mediatek_filogic/patches/25-platform.patch
--- a/devices/mediatek_filogic/patches/25-platform.patch
+++ b/devices/mediatek_filogic/patches/25-platform.patch
@@ -1,17 +1,80 @@
 --- a/target/linux/mediatek/filogic/base-files/lib/upgrade/platform.sh
 +++ b/target/linux/mediatek/filogic/base-files/lib/upgrade/platform.sh
-@@ -66,32 +66,19 @@ platform_do_upgrade() {
- 	local board=$(board_name)
- 
- 	case "$board" in
--	abt,asr3000|\
- 	bananapi,bpi-r3|\
- 	bananapi,bpi-r3-mini|\
- 	bananapi,bpi-r4|\
- 	bananapi,bpi-r4-poe|\
+@@ -110,7 +110,6 @@ platform_do_upgrade() {
+ 	bananapi,bpi-r4-lite|\
+ 	bazis,ax3000wm|\
  	cmcc,a10-ubootmod|\
 -	cmcc,rax3000m|\
+ 	comfast,cf-wr632ax-ubootmod|\
+ 	creatlentem,clt-r30b1-ubi|\
  	cudy,tr3000-v1-ubootmod|\
+@@ -120,11 +119,7 @@ platform_do_upgrade() {
+ 	cudy,wr3000h-v1-ubootmod|\
+ 	cudy,wr3000p-v1-ubootmod|\
+ 	gatonetworks,gdsp|\
+-	h3c,magic-nx30-pro|\
+ 	imou,hx21|\
+-	jcg,q30-pro|\
+-	jdcloud,re-cp-03|\
+-	konka,komi-a31|\
+ 	mediatek,mt7981-rfb|\
+ 	mediatek,mt7988a-rfb|\
+ 	mercusys,mr90x-v1-ubi|\
+@@ -132,19 +127,11 @@ platform_do_upgrade() {
+ 	netis,nx30v2|\
+ 	netis,nx31|\
+ 	netis,nx32u|\
+-	nokia,ea0326gmp|\
+ 	openwrt,one|\
+-	netcore,n60|\
+-	netcore,n60-pro|\
+-	qihoo,360t7|\
+ 	qihoo,360t7-ubi|\
+ 	routerich,ax3000-ubootmod|\
+ 	routerich,be7200|\
+ 	snr,snr-cpe-ax2|\
+-	tplink,tl-xdr4288|\
+-	tplink,tl-xdr6086|\
+-	tplink,tl-xdr6088|\
+-	tplink,tl-xtr8488|\
+ 	xiaomi,mi-router-ax3000t-ubootmod|\
+ 	xiaomi,redmi-router-ax6000-ubootmod|\
+ 	xiaomi,mi-router-wr30u-ubootmod|\
+@@ -157,6 +144,9 @@ platform_do_upgrade() {
+ 	acer,vero-w6m|\
+ 	airpi,ap3000m|\
+ 	arcadyan,mozart|\
++	cmcc,rax3000m-emmc|\
++	cmcc,xr30-emmc|\
++	sl,3000-emmc|\
+ 	glinet,gl-mt2500|\
+ 	glinet,gl-mt2500-airoha|\
+ 	glinet,gl-mt6000|\
+@@ -284,13 +274,6 @@ platform_do_upgrade() {
+ 			;;
+ 		esac
+ 		;;
+-	xiaomi,mi-router-ax3000t|\
+-	xiaomi,mi-router-wr30u-stock|\
+-	xiaomi,redmi-router-ax6000-stock)
+-		CI_KERN_UBIPART=ubi_kernel
+-		CI_ROOT_UBIPART=ubi
+-		nand_do_upgrade "$1"
+-		;;
+ 	*)
+ 		nand_do_upgrade "$1"
+ 		;;
+@@ -316,7 +299,6 @@ platform_check_image() {
+ 	bananapi,bpi-r4-lite|\
+ 	bazis,ax3000wm|\
+ 	cmcc,a10-ubootmod|\
+-	cmcc,rax3000m|\
+ 	comfast,cf-wr632ax-ubootmod|\
+ 	creatlentem,clt-r30b1-ubi|\
+ 	cudy,tr3000-v1-ubootmod|\
+@@ -326,25 +308,14 @@ platform_check_image() {
+ 	cudy,wr3000h-v1-ubootmod|\
+ 	cudy,wr3000p-v1-ubootmod|\
  	gatonetworks,gdsp|\
 -	h3c,magic-nx30-pro|\
 -	jcg,q30-pro|\
@@ -20,11 +83,13 @@
  	mediatek,mt7981-rfb|\
  	mediatek,mt7988a-rfb|\
  	mercusys,mr90x-v1-ubi|\
- 	netis,nx31|\
 -	nokia,ea0326gmp|\
+ 	netis,eap930-v1|\
+ 	netis,nx32u|\
  	openwrt,one|\
 -	netcore,n60|\
 -	qihoo,360t7|\
+ 	qihoo,360t7-ubi|\
  	routerich,ax3000-ubootmod|\
 -	tplink,tl-xdr4288|\
 -	tplink,tl-xdr6086|\
@@ -33,17 +98,45 @@
  	xiaomi,mi-router-ax3000t-ubootmod|\
  	xiaomi,redmi-router-ax6000-ubootmod|\
  	xiaomi,mi-router-wr30u-ubootmod|\
-@@ -169,13 +157,6 @@ platform_do_upgrade() {
- 			;;
- 		esac
+@@ -394,6 +365,9 @@ platform_copy_config() {
+ 	acer,vero-w6m|\
+ 	airpi,ap3000m|\
+ 	arcadyan,mozart|\
++	cmcc,rax3000m-emmc|\
++	cmcc,xr30-emmc|\
++	sl,3000-emmc|\
+ 	glinet,gl-mt2500|\
+ 	glinet,gl-mt2500-airoha|\
+ 	glinet,gl-mt6000|\
+@@ -416,6 +390,18 @@ platform_copy_config() {
+ 	esac
+ }
+ 
++tenbay_dualboot_fixup()
++{
++	[ "$(rootfs_type)" = "tmpfs" ] || return 0
++
++	if ! fw_printenv -n boot_from &>/dev/null; then
++		echo "unable to read uboot-env"
++		return 1
++	fi
++
++	fw_setenv boot_from ubi
++}
++
+ platform_pre_upgrade() {
+ 	local board=$(board_name)
+ 
+@@ -435,10 +421,8 @@ platform_pre_upgrade() {
+ 	jiorouter,ax6000-jidu6101)
+ 		jiorouter_initial_setup
  		;;
 -	xiaomi,mi-router-ax3000t|\
--	xiaomi,mi-router-wr30u|\
--	xiaomi,redmi-router-ax6000)
--		CI_KERN_UBIPART=ubi_kernel
--		CI_ROOT_UBIPART=ubi
--		nand_do_upgrade "$1"
--		;;
- 	*)
- 		nand_do_upgrade "$1"
+-	xiaomi,mi-router-wr30u-stock|\
+-	xiaomi,redmi-router-ax6000-stock)
+-		xiaomi_initial_setup
++	cmcc,mr3000d-ciq-256m)
++		tenbay_dualboot_fixup
  		;;
+ 	esac
+ }
